### ISSUE TITLE
Struggling to reproduce results of the paper

### ISSUE THREAD

**Issue by mobassir94** [dyabel/AnyTool#12]
Hi,
Thank you for sharing your impressive work with the community. I have been attempting to reproduce the results presented in your paper using Azure OpenAI's GPT-4o model, along with the ToolBench key provided after completing the form that you've shared. I carefully followed the instructions outlined in the README.md file. However, despite my efforts, I have been unable to achieve a pass rate comparable to what is reported in your paper.

To provide you with a clear understanding of my findings, I have attached a zip file named G1_instruction.zip. This file contains the results of running the G1_instruction dataset. Upon examining the outputs, I found multiple JSON files and text files, including success_cnt.txt. Using the data from success_cnt.txt, I wrote a script to calculate the pass rate by implementing Equation 2 as described in your paper. The results I obtained indicate a pass rate of 8.00%. Additionally, I encountered 35 timeouts, which accounted for 31.82% of the cases. Out of the 195 total examples, 6 were solved successfully, while 69 remained unsolved, and 35 were categorized as timed out. Furthermore, 85 examples were marked as unsolvable by humans.

These findings show a significant discrepancy between the results I obtained and those reported in your paper. The pass rate, in particular, is far lower than expected, and the number of timeouts, unsolved cases, and examples marked as "unsolvable by humans" is notably high.

I would greatly appreciate your guidance on what might be causing this discrepancy. Are there any additional steps, configurations, or considerations I might have overlooked that are essential for reproducing your results, particularly for the G1_instruction dataset? My goal is to achieve a pass rate similar to the one you reported in your paper, and I would be grateful for any advice or clarification you could provide.

Thank you for your time and support. I look forward to your response.
[G1_instruction.zip](https://github.com/user-attachments/files/17892177/G1_instruction.zip)

**Comment by dyabel** [comment]
The rapidapi server has changed a lot since our work published. Many APIs in the ToolBench has been deprecated. You can try with the [StableToolBench](https://github.com/THUNLP-MT/StableToolBench which) which uses the cache of API responses. And we will provide our logs with the original ToolBench later.

**Comment by dyabel** [comment]
> Hi, Thank you for sharing your impressive work with the community. I have been attempting to reproduce the results presented in your paper using Azure OpenAI's GPT-4o model, along with the ToolBench key provided after completing the form that you've shared. I carefully followed the instructions outlined in the README.md file. However, despite my efforts, I have been unable to achieve a pass rate comparable to what is reported in your paper.
> 
> To provide you with a clear understanding of my findings, I have attached a zip file named G1_instruction.zip. This file contains the results of running the G1_instruction dataset. Upon examining the outputs, I found multiple JSON files and text files, including success_cnt.txt. Using the data from success_cnt.txt, I wrote a script to calculate the pass rate by implementing Equation 2 as described in your paper. The results I obtained indicate a pass rate of 8.00%. Additionally, I encountered 35 timeouts, which accounted for 31.82% of the cases. Out of the 195 total examples, 6 were solved successfully, while 69 remained unsolved, and 35 were categorized as timed out. Furthermore, 85 examples were marked as unsolvable by humans.
> 
> These findings show a significant discrepancy between the results I obtained and those reported in your paper. The pass rate, in particular, is far lower than expected, and the number of timeouts, unsolved cases, and examples marked as "unsolvable by humans" is notably high.
> 
> I would greatly appreciate your guidance on what might be causing this discrepancy. Are there any additional steps, configurations, or considerations I might have overlooked that are essential for reproducing your results, particularly for the G1_instruction dataset? My goal is to achieve a pass rate similar to the one you reported in your paper, and I would be grateful for any advice or clarification you could provide.
> 
> Thank you for your time and support. I look forward to your response. [G1_instruction.zip](https://github.com/user-attachments/files/17892177/G1_instruction.zip)

Hi, I have uploaded my logs here https://drive.google.com/file/d/1-ARh87n82o4t1QM4tT59WU9L6oehF2bN/view?usp=sharing
